name: rgb-weaver
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python>=3.8,<3.13
  
  # Core dependencies
  - gdal>=3.4
  - rasterio>=1.3.0
  - numpy>=1.20.0
  - click>=8.0
  - tqdm>=4.60.0
  
  # Additional utilities
  - mercantile  
  - pillow>=8.0  
  
  - pytest>=6.0
  - pytest-cov
  - black
  - flake8
  - pre-commit
  
  # Pip dependencies 
  - pip
  - pip:
    - git+https://github.com/Australes-Inc/mbutil.git
    - git+https://github.com/Australes-Inc/rio-rgbify.git
