name: rgb-weaver
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python>=3.8,<3.13
  
  # Core dependencies
  - gdal>=3.4
  - rasterio>=1.3.0
  - numpy>=1.20.0
  - click>=8.0
  - tqdm>=4.60.0
  
  # Additional utilities
  - mercantile  # Pour les calculs de tiles
  - pillow>=8.0  # Pour le traitement d'images
  
  - pytest>=6.0
  - pytest-cov
  - black
  - flake8
  - pre-commit
  
  # Pip dependencies 
  - pip
  - pip:
    - git+https://github.com/Australes-Inc/mbutil.git
    - git+https://github.com/Australes-Inc/rio-rgbify.git

# Instructions d'installation
# 1. Créer l'environnement:
#    conda env create -f environment.yml
#
# 2. Activer l'environnement:
#    conda activate rgb-weaver
#
# 3. Installer rgb-weaver en mode développement:
#    pip install -e .
#
# 4. Vérifier l'installation:
#    rgb-weaver --help